// Engineering digest: the OSS-side artifact of the hosted tier's "weekly
// engineering digest". Reads the current graph — stats, health, hub
// concentration, community sizes, build provenance, and the cost report —
// and renders a shareable markdown brief (stdout or .astria/digest.md).
// Deterministic and LLM-free; cron/CI friendly:
//   astria digest --out .astria/digest.md

import * as pathMod from 'path';
import { existsSync, readFileSync } from 'fs';
import { graphStats, healthReport, godNodes, listCommunities, graphBuildInfo } from '../native';

export interface DigestOptions {
  graph: string;
  out?: string;
  json?: boolean;
}

function healthEmoji(grade: string): string {
  switch (grade.toUpperCase()) {
    case 'A': return '🟢';
    case 'B': return '🟢';
    case 'C': return '🟡';
    case 'D': return '🟠';
    default: return '🔴';
  }
}

function relativeTime(unixSeconds: string | null | undefined): string {
  const t = Number(unixSeconds);
  if (!Number.isFinite(t) || t <= 0) return 'unknown';
  const minutes = Math.round((Date.now() / 1000 - t) / 60);
  if (minutes < 60) return `${minutes} min ago`;
  if (minutes < 60 * 24) return `${Math.round(minutes / 60)} h ago`;
  return `${Math.round(minutes / (60 * 24))} days ago`;
}

export async function digestCommand(opts: DigestOptions) {
  try {
    const stats = graphStats(opts.graph);
    const health = healthReport(opts.graph);
    const hubs = godNodes(opts.graph) as { id: string; label: string; degree: number; community: string | null }[];
    const communities = listCommunities(opts.graph);
    const build = graphBuildInfo(opts.graph);

    const hubShare = stats.nodeCount > 0 ? hubs.length / stats.nodeCount : 0;
    const topCommunities = (communities.communities || [])
      .slice(0, 5)
      .map((c: any) => `| ${c.label} | ${c.size} | ${c.cohesion ?? '-'} | ${c.labelSource === 'llm' ? 'LLM' : 'hub'} |`);

    let costBlock = '';
    const costPath = pathMod.join(opts.graph, '.astria', 'cost.json');
    if (existsSync(costPath)) {
      try {
        const cost = JSON.parse(readFileSync(costPath, 'utf-8'));
        const cum = cost.cumulative || {};
        costBlock = [
          '',
          '### LLM spend',
          '',
          `- Lifetime semantic enrichment: ${cum.input_tokens ?? 0} input + ${cum.output_tokens ?? 0} output tokens across ${cum.runs ?? 0} completed runs (${cum.api_calls ?? 0} API calls)`,
          cost.estimated_cost_usd
            ? `- Estimated cost: $${Number(cost.estimated_cost_usd.cumulative).toFixed(4)} (operator-supplied rates)`
            : '- Estimated cost: n/a (set ASTRIA_COST_*_PER_MTOK for a dollar estimate)',
        ].join('\n');
      } catch {
        // unreadable cost.json — omit the block
      }
    }

    const markdown = `# Engineering digest — ${new Date().toISOString().slice(0, 10)}

## Graph overview

| Metric | Value |
|--------|-------|
| Nodes | ${stats.nodeCount} |
| Edges | ${stats.edgeCount} |
| Communities | ${stats.communityCount} |
| Files tracked | ${stats.fileCount} |
| Last built | ${relativeTime(build?.graphPublishedAt)} by astria ${build?.astriaVersion ?? 'n/a'} |

## Code health

${healthEmoji(health.grade)} **Score ${health.score}/100 (grade ${health.grade})**

- Unreachable-symbol candidates: ${health.deadCode.length}
- Circular file dependencies: ${health.cycles.length}
- Hub concentration: ${hubs.length} hubs (${(hubShare * 100).toFixed(1)}% of nodes)

${health.cycles.length ? `- ⚠️ ${Math.min(health.cycles.length, 5)} cycle(s), e.g. ${health.cycles.slice(0, 3).join('; ')}` : '- No file cycles detected'}

## Where the complexity lives

Top hubs (what everything routes through — change with care):

${hubs.slice(0, 5).map((h) => `- \`${h.label}\` — degree ${h.degree}${h.community ? ` (${h.community})` : ''}`).join('\n') || '- none'}

Largest communities:

| Community | Size | Cohesion | Label source |
|-----------|------|----------|--------------|
${topCommunities.join('\n') || '| — | — | — | — |'}
${costBlock}

---
*Generated by \`astria digest\` — deterministic, from the local knowledge graph. Schedule it (cron/CI) for a weekly cadence, or read it via the hosted tier at app.graphify.com.*
`;

    if (opts.json) {
      console.log(JSON.stringify({
        generated_at: new Date().toISOString(),
        stats,
        health: { score: health.score, grade: health.grade, dead_code: health.deadCode.length, cycles: health.cycles.length },
        hubs: hubs.slice(0, 5),
        communities: (communities.communities || []).slice(0, 5),
        build,
      }, null, 2));
      return;
    }

    if (opts.out) {
      const { writeFileSync, mkdirSync } = await import('fs');
      mkdirSync(pathMod.dirname(opts.out), { recursive: true });
      writeFileSync(opts.out, markdown);
      console.log(`Digest written: ${opts.out}`);
    } else {
      console.log(markdown);
    }
  } catch (e: any) {
    console.error(`Error: ${e.message || e}`);
    process.exitCode = 1;
  }
}
